- tools/github-repo-configurator/README.md
- tools/github-repo-configurator/default-repo-config.yaml
Provide additional default issues:
- Release to NuGet.org
- Release to MyGet.org
- Define branch policies
- Provide CI badge
> Provide additional default issues

- tools/github-repo-configurator/default-repo-config.yaml
> Add Netlify to setup

- README.md
Introduce Netlify badge for #54
> Introduce Netlify badge

- tools/github-repo-configurator/README.md
- tools/github-repo-configurator/default-pypi-repo-config.yaml
- tools/github-repo-configurator/src/Arcus.Tools.Repository.App/GitHub/GitHubRepository.cs
Enhanced exception message, fixing issue #57
> Config exception fix

- CODE_OF_CONDUCT.md
Introduce a Code Of Conduct.
Relates to #54
> Introduce a Code Of Conduct

- community/blog/2020-03-Releasing-Arcus-Messaging-and-BackgroundJobs-v.0.1.0/README.md
Provide "What's Next" for "Announcing Arcus Messaging & Background Jobs" blog post.
Relates to https://github.com/arcus-azure/arcus.backgroundjobs/issues/31
Relates to https://github.com/arcus-azure/arcus.messaging/issues/67
> Provide "What's Next" for "Announcing Arcus Messaging & Background Jobs" blog post

- community/blog/2020-04-Releasing-Arcus-Templates-v0.2.0/README.md
- tools/github-repo-configurator/src/Arcus.Tools.Repository.App/Arcus.Tools.Repository.App.csproj
Relates to https://github.com/arcus-azure/arcus.templates/issues/113
> Blog - add blog post for releasing Arcus.Templates v0.2.0

- community/blog/2020-04-Announcing-Arcus-Observability-v0.1/README.md
Relates to https://github.com/arcus-azure/arcus.observability/issues/32
> Blog - propose write-up for announcing Observability v0.1

- community/blog/2020.10-Introducing improved message flow control with Azure Service Bus in Arcus Messaging/README.md
- community/blog/2020.10-Introducing-message-handling-with-Azure-Service-Bus-message-influence/README.md
Writing a new blog post proposal for the major feature release of the influence of Azure Service Bus message operations during message handling.
Closes #94
> Blog - blog post for Arcus.Messaging v0.4-v0.5

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/blogpost-proposal.md
- .github/ISSUE_TEMPLATE/documentation-request.md
> Provide new issue templates

- docs/README.md
- docs/_blogposts/announcing-arcus-observability.md
- docs/_config.yml
- docs/_data/menus.yml
- docs/_layouts/blogposts.html
- docs/_layouts/home.html
- docs/_usecases/secret-management.md
- docs/_usecases/secret-store.md
- docs/blogposts.md
- docs/components.md
- docs/usecases.md
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
> Provide a list of all blog posts on arcus-azure.net

- docs/_blogposts/2019-the-year-arcus-started-growing.md
- docs/_blogposts/announcing-arcus-messaging-and-background-jobs.md
- docs/_blogposts/announcing-arcus-scripting.md
- docs/_blogposts/announcing-arcus.md
- docs/_blogposts/arcus-web-api-v1-0.md
- docs/_blogposts/integrating-arcus-api-security-filters-within-f-sharp-giraffe-function-pipelines.md
- docs/_blogposts/introducing-more-message-flow-control-Arcus-messaging.md
- docs/_blogposts/introducing-secret-store.md
- docs/_blogposts/making-arcus-templates-more-powerful.md
- docs/_blogposts/measure-a-variety-of-azure-dependencies-with-observability-v0.2.md
- docs/_blogposts/role-based-authorization-with-arcus-secret-store.md
- docs/_config.yml
- docs/_layouts/blogposts.html
- docs/_layouts/home.html
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
Fixes #102
> Import all existing blog posts to arcus-azure.net

- community/blog/2021-10 Making the secret store more powerful in Arcus.Security v1.4/README.md
Creates a new blog post proposal about some of the new major updates in Arcus.Security v1.4.
Closes #109
> Blog - making the secret store more powerfull in Arcus.Security v1.4

- docs/_blogposts/making-the-secret-store-more-powerful-in-arcus-security-v1.4.md
Relates to https://github.com/arcus-azure/arcus/issues/109
> Docs - add blog post reference for new post about Arcus security v1.4

- docs/_blogposts/explaining-the-magic-of-the-arcus-.net-project-templates.md
A new blog post was released: https://www.codit.eu/blog/arcus-net-project-templates/ , so a new reference is added here.
> feat: add blog post for Arcus project templates

- community/blog/2021-05 Enhanced request tracking in Arcus.WebApi v1.3/README.md
New blog post for the v1.3 release of the Arcus Web API repo.
Closes #132
> feat: add blog post for enhanded request tracking in web api v1.3

- docs/_blogposts/enhanced-request-tracking-in-arcus-web-api-v1.3.md
New blog post at https://www.codit.eu/blog/enhanced-request-tracking-in-arcus-web-api-v1-3/
> feat: add blog post for enhanced request tracking

- docs/_blogposts/the-power-of-the-arcus-secret-store.md
Add new blog post at https://www.codit.eu/blog/the-power-of-the-arcus-secret-store/
> feat: add blog post power of secret store

- docs/_blogposts/taking-messaging-to-the-next-level-with-arcus-messaging-v1.0.md
New blog post at https://www.codit.eu/blog/taking-messaging-to-the-next-level-with-arcus-messaging-v1-0/
> feat: add blog post messaging v1.0

- .github/CODEOWNERS
Unfortunately, I don't have the time that I was hoping to have which means that I can no longer actively contribute - Sorry!
Feel free to remove me from the rest as well.
> chore: Remove @tomkerkhove as code owner

- .github/CODEOWNERS
Added new code-owners to general repository.
> chore: update with new code-owners

- docs/_blogposts/2021-the-year-arcus-matured.md
Add blog post reference for our new 2021 overview blog post.
> feat: add blog post reference for 2021 overview

- community/blog/2022-02 Service correlation preparation and .NET 6 support in Arcus Observability v2.4/README.md
Adds blog post for the Arcus Observability v2.4 release.
Relates #189
> feat: add blog for observability v2.4 release updates

- docs/_blogposts/service-correlation-preparation-net-6-support-in-arcus-observability-v2.4.md
"Service Correlation Preparation & .NET 6 Support in Arcus Observability v2.4" is published. Let's reference it.
Closes #189
> feat: add blog post reference to new observability post

- docs/_blogposts/property-based-testing-the-arcus-python-implementations-for-streamlined-ml-development.md
Adds a new blog post reference.
> feat: add property-based testing ML blog post reference

- community/blog/2022-04 Interesting new hooks and .NET 6 support in Arcus WebAPI v1.5/README.md
Creates blog post proposal on the new Arcus WebAPI v1.5 release.
Relates to #200
> feat: add blog on web api v1.5

- community/blog/2022-04 Interesting new hooks and .NET 6 support in Arcus WebAPI v1.5/README.md
Since we're talking about .NET 6 support in this version, we can use .NET 6 code samples in our blog, too.
Follow-up of #202 
Relates to #200
> fix: update Arcus WebAPI v1.5 blog with .NET 6 code samples

- .github/ISSUE_TEMPLATE/blogpost-proposal.md
Remove the unnecessary paragraph in the blog post issue tempalte, as the outline of the blog post and how it would help seems already enough here.
> chore: remove unnecessary paragraph in blog post proposal issue template

- docs/_blogposts/service-to-service-correlation-one-of-the-biggest-arcus-features-in-observability-v2.5.md
Add Observability v2.5 blog post reference.
Closes #255
> feat: add v2.5 observability blog post reference

- docs/_blogposts/arcus-templates-v1.0-a-major-release-with-major-features.md
Add blog post reference for Templates v1.0 blog post.
https://www.codit.eu/blog/arcus-templates-v1-0-a-major-release-with-major-features/
> chore: create templates v1.0 blog post ref

- website/resources/posts/2022: The Year Arcus Grew Up.md
Add blog post ref for summary blog post of Arcus 2022.
> feat: add arcus 2022 blog post ref

- website/resources/posts/Rethinking Event Publishing in Arcus EventGrid v3.3.md
Add blog post reference for Arcus EventGrid v3.3.
Closes #257
> feat: add eventgrid v3.3 blog post reference

- website/resources/posts/Synchronous Secret Retrieval in Arcus Security v1.9.md
Add Arcus Security v1.9 blog post reference.
Closes #260
> chore: add security v1.9 blog post ref

- website/resources/components/background-jobs.md
Correct the background jobs component description w/ the same description we have on the feature documentation site of background jobs.
> chore: correct background jobs component description

- website/resources/components/azure-ml.md
- website/resources/components/background-jobs.md
- website/resources/components/event-grid.md
- website/resources/components/messaging.md
- website/resources/components/ml.md
- website/resources/components/observability.md
- website/resources/components/security.md
- website/resources/components/templates.md
- website/resources/components/web-api.md
Simplify the component descriptions to a single, short sentence.
Closes #293
> docs: simplify component descriptions

- community/blog/2023-01 Role-based authentication in Azure API Management made easy in Arcus Scripting v0.8/README.md
Add blog post proposal for Arcus Scripting v0.8 release.
Relates to #289
> feat: add scripting v0.8 blog post proposal

- website/resources/posts/Fully Integrating with Microsoft Technology in Arcus Messaging v1.4.md
Adding blog post reference of Arcus Messaging v1.4 release.
Closes #282
> chore: add Arcus messaging v1.4 blog post reference

- community/blog/2023-01 Provide built-in W3C correlation in Arcus Templates v1.1/README.md
Provide blog post proposal for Arcus Templates v1.1 release.
Relates to #298
> feat: add templates v1.1 blog post proposal

- website/resources/pages/use-cases.mdx
- website/resources/posts/Synchronous Secret Retrieval in Arcus Security v1.9.md
PR fixes a wrong date format in one of the posts which caused a JS exception.
PR also fixes a small typo in the use cases page.
> fix: blog page read more action

- website/resources/components/background-jobs.md
- website/resources/components/messaging.md
- website/resources/components/scripting.md
- website/resources/components/templates.md
Feature the most popular Arcus components on the index page.
> chore: feature most popular components

- website/resources/posts/Provide Built-in W3C Correlation and Isolated Azure Functions in Arcus Templates v1.1.md
- website/resources/posts/Role-Based Authentication in Azure API Management Made Easy in Arcus Scripting v0.8.md
- website/resources/posts/The Final W3C Correlation Puzzle Piece in Arcus Observability v2.7.md
- website/resources/posts/W3C Service-to-Service Correlation in Newest Arcus Releases.md
Add missing Arcus blog post references.
> chore: add missing arcus blog posts refs

- docs/_blogposts/Integrating Arcus Security in a Non-Invasive Manner.md
Add new blog post reference for the non-invasive Arcus Security blog post.
> chore: add arcus security non-invasive blog post reference

- website/resources/posts/Rebranding Arcus for Maximum Adoption.md
Add blog reference to new Arcus rebranding post.
> chore: add 'Rebranding Arcus for Maximum Adoption' blog ref

- website/resources/posts/New Azure Logic Apps and DevOps Functionality in Milestone v1.0 Arcus Scripting Release.md
Add a reference to the Scripting v1.0 blog post.
Closes #325
> feat: add scripting v1.0 blog post reference

- community/blog/2024-01 First Arcus (Observability) release of 2024 starts with a bang/README.md
Add blog post on the Observability v3.0 release.
Relates to #345
> feat: add observability v3.0 post

- community/blog/2024-03 The Arcus Web API v2.0 release reconciles with automatic Microsoft Tracking/README.md
Adds run down blog post of Web API v2.0 release.
> feat: add web api v2.0 blog post

- community/blog/2024-03 The big Arcus Messaging v2.0 release is bigger than its parts/README.md
Adds a new post on the run down of the Messaging v2.0 release.
> feat: add messaging v2.0 blog post
